import { promises as fs } from 'fs';
import path from 'path';

export class ServerManager {
    constructor(launcher) {
        this.launcher = launcher;
        this.logger = launcher.logger.createChild('ServerManager');
        this.serversDirectory = path.join(launcher.options.gameDirectory, 'servers');
        this.runningServers = new Map();
        this.ensureDirectories().catch(err => {
            this.logger.warn('Server directories creation skipped:', err.message);
        });
        this.logger.info('Server Manager initialized');
    }

    async ensureDirectories() {
        const dirs = [
            this.serversDirectory,
            path.join(this.serversDirectory, 'configs'),
            path.join(this.serversDirectory, 'worlds'),
            path.join(this.serversDirectory, 'logs'),
            path.join(this.serversDirectory, 'backups')
        ];
        await Promise.all(dirs.map(async dir => {
            try {
                await fs.access(dir);
            } catch {
                await fs.mkdir(dir, { recursive: true });
                this.logger.debug(`Created directory: ${dir}`);
            }
        }));
    }

    async createServer(config) {
        this.logger.info('Creating new server configuration', config);
        const serverId = config.id || `server_${Date.now()}`;
        const serverPath = path.join(this.serversDirectory, serverId);
        await fs.mkdir(serverPath, { recursive: true });

        const defaultConfig = {
            id: serverId,
            name: config.name || `Server ${serverId}`,
            version: config.version || this.launcher.options.version,
            gameMode: config.gameMode || 'survival',
            difficulty: config.difficulty || 'normal',
            maxPlayers: config.maxPlayers || 20,
            port: config.port || 25565,
            onlineMode: config.onlineMode !== false,
            whitelist: config.whitelist || false,
            pvp: config.pvp !== false,
            spawnProtection: config.spawnProtection || 16,
            viewDistance: config.viewDistance || 10,
            seed: config.seed || '',
            motd: config.motd || 'A Minecraft Server',
            levelType: config.levelType || 'default',
            generateStructures: config.generateStructures !== false,
            hardcore: config.hardcore || false,
            enableCommandBlock: config.enableCommandBlock || false,
            allowNether: config.allowNether !== false,
            allowFlight: config.allowFlight || false,
            forceGamemode: config.forceGamemode || false,
            enableQuery: config.enableQuery || false,
            enableRcon: config.enableRcon || false,
            rconPort: config.rconPort || 25575,
            rconPassword: config.rconPassword || '',
            resourcePack: config.resourcePack || '',
            resourcePackSha1: config.resourcePackSha1 || '',
            createdAt: new Date().toISOString(),
            lastModified: new Date().toISOString(),
            autoStart: config.autoStart || false,
            memory: config.memory || '2G',
            javaArgs: config.javaArgs || '',
            plugins: config.plugins || [],
            mods: config.mods || []
        };

        await fs.writeFile(path.join(serverPath, 'server.properties'), this.generatePropertiesFile(defaultConfig), 'utf8');
        await fs.writeFile(path.join(serverPath, 'server.json'), JSON.stringify(defaultConfig, null, 2), 'utf8');

        await Promise.all(['worlds', 'logs', 'backups', 'plugins', 'mods', 'config'].map(subDir =>
            fs.mkdir(path.join(serverPath, subDir), { recursive: true })
        ));

        this.logger.info('Server configuration created', { id: serverId, path: serverPath });
        return defaultConfig;
    }

    generatePropertiesFile(config) {
        const props = [
            `#Minecraft server properties`,
            `#${new Date().toISOString()}`,
            `#Generated by MC Launcher Core`,
            `motd=${config.motd}`,
            `level-name=${config.id}`,
            `gamemode=${config.gameMode === 'creative' ? 1 : config.gameMode === 'adventure' ? 2 : 0}`,
            `difficulty=${config.difficulty === 'peaceful' ? 0 : config.difficulty === 'easy' ? 1 : config.difficulty === 'normal' ? 2 : 3}`,
            `hardcore=${config.hardcore}`,
            `pvp=${config.pvp}`,
            `allow-flight=${config.allowFlight}`,
            `enable-command-block=${config.enableCommandBlock}`,
            `max-players=${config.maxPlayers}`,
            `online-mode=${config.onlineMode}`,
            `allow-nether=${config.allowNether}`,
            `spawn-protection=${config.spawnProtection}`,
            `view-distance=${config.viewDistance}`,
            `generate-structures=${config.generateStructures}`,
            `level-type=${config.levelType}`,
            `force-gamemode=${config.forceGamemode}`,
            `enable-query=${config.enableQuery}`,
            `enable-rcon=${config.enableRcon}`,
            `rcon.port=${config.rconPort}`,
            `rcon.password=${config.rconPassword}`,
            `seed=${config.seed}`,
            `resource-pack=${config.resourcePack}`,
            `resource-pack-sha1=${config.resourcePackSha1}`,
            `server-port=${config.port}`,
            `whitelist=${config.whitelist}`,
            `max-world-size=29999984`,
            `network-compression-threshold=256`,
            `max-build-height=256`,
            `prevent-proxy-connections=false`,
            `use-native-transport=true`,
            `enable-status=true`,
            `broadcast-rcon-to-ops=true`,
            `broadcast-console-to-ops=true`,
            `sync-chunk-writes=true`,
            `require-resource-pack=false`,
            `entity-broadcast-range-percentage=100`,
            `simulation-distance=10`,
            `function-permission-level=2`,
            `rate-limit=0`,
            `player-idle-timeout=0`
        ];
        return props.join('\n');
    }

    async loadServer(serverId) {
        this.logger.info(`Loading server configuration: ${serverId}`);
        const metaPath = path.join(this.serversDirectory, serverId, 'server.json');
        try {
            await fs.access(metaPath);
        } catch {
            throw new Error(`Server not found: ${serverId}`);
        }
        const configData = JSON.parse(await fs.readFile(metaPath, 'utf8'));
        configData.lastLoaded = new Date().toISOString();
        this.logger.info(`Server configuration loaded: ${serverId}`);
        return configData;
    }

    async listServers() {
        this.logger.debug('Listing servers');
        const servers = [];
        const skipDirs = ['configs', 'worlds', 'logs', 'backups'];
        try {
            const serverDirs = await fs.readdir(this.serversDirectory);
            for (const serverId of serverDirs) {
                if (skipDirs.includes(serverId)) continue;
                const metaPath = path.join(this.serversDirectory, serverId, 'server.json');
                try {
                    const configData = JSON.parse(await fs.readFile(metaPath, 'utf8'));
                    configData.isRunning = this.runningServers.has(serverId);
                    servers.push(configData);
                } catch {
                    this.logger.warn(`Invalid server directory: ${serverId}`);
                }
            }
        } catch {
            // 服务端目录不存在或为空
        }
        this.logger.debug(`Found ${servers.length} servers`);
        return servers;
    }

    async startServer(serverId, options = {}) {
        this.logger.info(`Starting server: ${serverId}`);
        if (this.runningServers.has(serverId)) {
            throw new Error(`Server already running: ${serverId}`);
        }

        const serverConfig = await this.loadServer(serverId);
        const serverPath = path.join(this.serversDirectory, serverId);
        const { args } = await this.generateServerLaunchArgs(serverConfig, serverPath, options);

        const { spawn } = await import('child_process');
        const serverProcess = spawn(this.launcher.options.javaPath, args, {
            cwd: serverPath,
            stdio: ['pipe', 'pipe', 'pipe'],
            detached: false
        });

        const processInfo = {
            process: serverProcess,
            config: serverConfig,
            startTime: Date.now(),
            logFile: path.join(serverPath, 'logs', `server_${Date.now()}.log`)
        };
        this.runningServers.set(serverId, processInfo);
        this.setupProcessHandlers(serverId, serverProcess, processInfo.logFile);

        this.logger.info(`Server started: ${serverId}`, {
            pid: serverProcess.pid,
            port: serverConfig.port
        });
        return serverProcess;
    }

    async generateServerLaunchArgs(serverConfig, serverPath, options) {
        const args = [];
        const mem = options.memory || serverConfig.memory || '2G';
        args.push(`-Xmx${mem}`, `-Xms${mem}`);
        if (serverConfig.javaArgs) {
            args.push(...serverConfig.javaArgs.split(' '));
        }

        const serverJarPath = path.join(serverPath, `minecraft_server.${serverConfig.version}.jar`);
        try {
            await fs.access(serverJarPath);
        } catch {
            this.logger.info(`Downloading server jar: ${serverConfig.version}`);
            await this.downloadServerJar(serverConfig.version, serverJarPath);
        }

        args.push('-jar', serverJarPath, 'nogui');
        return { args, serverJarPath, timestamp: new Date().toISOString() };
    }

    setupProcessHandlers(serverId, process, logFile) {
        const logStreamPromise = this.createLogStream(logFile);

        const writeLog = async (prefix, data) => {
            try {
                const logStream = await logStreamPromise;
                logStream.write(`[${prefix}] ${data.toString()}`);
            } catch (error) {
                this.logger.error(`Failed to write to log file: ${logFile}`, error);
            }
        };

        process.stdout.on('data', data => {
            this.logger.debug(`[${serverId}] stdout:`, data.toString());
            writeLog('STDOUT', data);
        });

        process.stderr.on('data', data => {
            this.logger.warn(`[${serverId}] stderr:`, data.toString());
            writeLog('STDERR', data);
        });

        const cleanup = () => {
            if (this.runningServers.has(serverId)) {
                this.runningServers.delete(serverId);
            }
        };

        process.on('close', code => {
            this.logger.info(`[${serverId}] Server process exited with code ${code}`);
            cleanup();
        });

        process.on('error', error => {
            this.logger.error(`[${serverId}] Server process error:`, error);
            cleanup();
        });
    }

    async createLogStream(logFile) {
        await fs.mkdir(path.dirname(logFile), { recursive: true });
        const { createWriteStream } = await import('fs');
        const stream = createWriteStream(logFile, { flags: 'a' });
        stream.write(`=== Server Log Started at ${new Date().toISOString()} ===\n`);
        return stream;
    }

    async stopServer(serverId, force = false) {
        this.logger.info(`Stopping server: ${serverId}`, { force });
        const processInfo = this.runningServers.get(serverId);
        if (!processInfo) {
            throw new Error(`Server not running: ${serverId}`);
        }

        const { process } = processInfo;
        if (force) {
            process.kill('SIGKILL');
        } else {
            process.stdin.write('stop\n');
            await new Promise((resolve, reject) => {
                const timeoutId = setTimeout(() => {
                    this.logger.warn(`Server ${serverId} did not stop gracefully, forcing kill`);
                    process.kill('SIGKILL');
                    reject(new Error('Server stop timeout'));
                }, 30000);
                process.once('close', () => {
                    clearTimeout(timeoutId);
                    resolve();
                });
            });
        }

        this.runningServers.delete(serverId);
        this.logger.info(`Server stopped: ${serverId}`);
        return {
            success: true,
            serverId,
            forceStopped: force,
            stopTime: new Date().toISOString()
        };
    }

    async restartServer(serverId) {
        this.logger.info(`Restarting server: ${serverId}`);
        if (this.runningServers.has(serverId)) {
            await this.stopServer(serverId, false);
            await new Promise(resolve => setTimeout(resolve, 2000));
        }
        const newProcess = await this.startServer(serverId);
        this.logger.info(`Server restarted: ${serverId}`);
        return newProcess;
    }

    async sendCommand(serverId, command) {
        this.logger.debug(`Sending command to server ${serverId}: ${command}`);
        const processInfo = this.runningServers.get(serverId);
        if (!processInfo) {
            throw new Error(`Server not running: ${serverId}`);
        }
        processInfo.process.stdin.write(`${command}\n`);
        this.logger.debug(`Command sent: ${command}`);
        return {
            success: true,
            serverId,
            command,
            sentAt: new Date().toISOString()
        };
    }

    async getServerStatus(serverId) {
        const processInfo = this.runningServers.get(serverId);
        const isRunning = !!processInfo;
        const status = {
            serverId,
            isRunning,
            uptime: 0,
            pid: 0,
            config: null
        };

        if (isRunning) {
            const { process, config, startTime } = processInfo;
            status.pid = process.pid;
            status.uptime = Date.now() - startTime;
            status.config = config;
            status.memoryUsage = process.memoryUsage ? process.memoryUsage() : null;
        } else {
            try {
                status.config = await this.loadServer(serverId);
            } catch {
                // 配置加载失败
            }
        }
        return status;
    }

    async backupServer(serverId, options = {}) {
        this.logger.info(`Creating backup for server: ${serverId}`, options);
        const serverPath = path.join(this.serversDirectory, serverId);
        const backupDir = path.join(serverPath, 'backups');
        await fs.mkdir(backupDir, { recursive: true });

        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const backupName = `backup_${timestamp}`;
        const backupPath = path.join(backupDir, backupName);

        const backupResult = await this.createBackup(serverPath, backupPath, options);

        this.logger.info(`Backup created: ${backupName}`, {
            size: backupResult.size,
            duration: backupResult.duration
        });
        return {
            success: true,
            serverId,
            backupName,
            backupPath,
            ...backupResult
        };
    }

    async createBackup(sourcePath, backupPath, options) {
        const startTime = Date.now();
        const { exec } = await import('child_process');
        const compressCommand = options.compress !== false
            ? `tar -czf "${backupPath}.tar.gz" -C "${sourcePath}" .`
            : `cp -r "${sourcePath}" "${backupPath}"`;
        const statsPath = options.compress !== false ? `${backupPath}.tar.gz` : backupPath;

        return new Promise((resolve, reject) => {
            exec(compressCommand, (error, stdout, stderr) => {
                if (error) {
                    reject(new Error(`Backup failed: ${stderr || error.message}`));
                    return;
                }
                const duration = Date.now() - startTime;
                fs.stat(statsPath)
                    .then(stats => resolve({
                        size: stats.size,
                        duration,
                        compressed: options.compress !== false,
                        timestamp: new Date().toISOString()
                    }))
                    .catch(() => resolve({
                        duration,
                        compressed: options.compress !== false,
                        timestamp: new Date().toISOString(),
                        size: null
                    }));
            });
        });
    }

    async downloadServerJar(version, destPath) {
        this.logger.info(`Downloading server jar for version ${version}`);
        const downloadUrl = `https://launcher.mojang.com/v1/objects/${await this.getServerJarHash(version)}/server.jar`;
        const response = await fetch(downloadUrl);
        if (!response.ok) {
            throw new Error(`Failed to download server jar: ${response.statusText}`);
        }
        const buffer = await response.arrayBuffer();
        await fs.writeFile(destPath, Buffer.from(buffer));
        this.logger.info(`Server jar downloaded: ${destPath}`);
    }

    async getServerJarHash(version) {
        const manifestResponse = await fetch('https://launchermeta.mojang.com/mc/game/version_manifest.json');
        if (!manifestResponse.ok) {
            throw new Error(`Failed to fetch version manifest: ${manifestResponse.statusText}`);
        }
        const manifest = await manifestResponse.json();
        const versionInfo = manifest.versions.find(v => v.id === version);
        if (!versionInfo) {
            throw new Error(`Version not found: ${version}`);
        }
        const versionResponse = await fetch(versionInfo.url);
        if (!versionResponse.ok) {
            throw new Error(`Failed to fetch version details: ${versionResponse.statusText}`);
        }
        const versionDetails = await versionResponse.json();
        if (!versionDetails.downloads.server) {
            throw new Error(`Server jar not found for version ${version}`);
        }
        return versionDetails.downloads.server.sha1;
    }

    async getStatus() {
        try {
            const servers = await this.listServers();
            const runningServers = [];
            for (const [serverId, processInfo] of this.runningServers.entries()) {
                runningServers.push({
                    serverId,
                    pid: processInfo.process.pid,
                    uptime: Date.now() - processInfo.startTime,
                    config: processInfo.config
                });
            }
            return {
                totalServers: servers.length,
                runningServers: runningServers.length,
                serversDirectory: this.serversDirectory,
                servers,
                runningServers,
                timestamp: new Date().toISOString()
            };
        } catch (error) {
            this.logger.error('Failed to get server manager status', error);
            return {
                error: error.message,
                serversDirectory: this.serversDirectory,
                timestamp: new Date().toISOString()
            };
        }
    }
}
